# use -f docker-compose.prod.yml to specify the use of this file
version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./app/static/fund.json:/app/static/fund.json
